apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
  labels:
    app: my-app
spec:
  selector:
    app: my-app  
  ports:
    - port: 80            
      targetPort: 80       
      nodePort: 30080     
  type: NodePort           